const obrasSociales = [
  'Particular',
  'Aca Salud',
  'Accord Salud',
  'Aceros Paraná (OSAP)',
  'AMC Solidaria',
  'AMR Salud',
  'APROSS',
  'Asociart ART',
  'Caja de Ingenieros',
  'Caja Forense',
  'Centro De Agentes De Propaganda Medica',
  'CUD',
  'DEMI Salud',
  'Federada Salud',
  'FIDEI - OSCEP',
  'Galeno',
  'Grupo Oroño SM',
  'Grupo San Nicolás (GSN)',
  'IAPOS',
  'IOMA',
  'IOSFA',
  'Jerárquicos Salud',
  'Locutores',
  'Luis Pasteur',
  'Medicina Esencial',
  'Medicus',
  'Medifé',
  'Medycin',
  'Mutual SAMI (San Nicolás)',
  'MUTUALYF',
  'Obra Social de Petroleros de Córdoba',
  'OMINT',
  'OSCTCP',
  'OSDE',
  'OSDOP',
  'OSJRA',
  'OSMISS',
  'OSPAC',
  'OSPE',
  'OSPESGA',
  'OSSEG',
  'OSUNR',
  'PAMI',
  'Pequeña familia',
  'Prevención Salud',
  'Proapro (2da Circ Sta Fe)',
  'Sanarte Asistencia Medica Privada',
  'Sancor Salud',
  'Servesalud',
  'SMATA',
  'Swiss Medical',
  'TV',
  'Unimed',
  'UOM',
  'UTHGRA',
];

const provincias = [
  'Ciudad de Buenos Aires y GBA',
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
];

module.exports = {
  obrasSociales,
  provincias,
};
